### ISSUE TITLE
Due Time

### ISSUE THREAD

**Issue by Yixuanhu0106** [MUSA611-CPLN692-spring2019/cpln692-week4#3]
Hi Nathan and Ross,

Could you clarify the due date? In the page, it is said that it's due Wednesday 2/8, which is a weird date. 

Thanks,
Emily

**Comment by rossbernet** [comment]
Emily,

Thank you for creating an issue. And thank you for pointing this out. I just updated it: Thursday, February 14. Homework will always be due the Thursday before class.

The explanation for this mistake: we are reusing labs and homework assignments from previous years. And although we have tried to update all the numbers/dates, we have missed a couple. I will try to be more diligent about this!

Thanks,
Ross
